version: "3.9"

networks:
  default:
    external:
      name: docker_default
services:
  mein-solar-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mein-solar-system
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mein-solar-system.rule=Host(`system.saturn.mein.nl`)"
      - "traefik.http.routers.mein-solar-system.entrypoints=websecure"
      - "traefik.http.routers.mein-solar-system.tls=true"
      - "traefik.http.routers.mein-solar-system.tls.certresolver=letencrypt"
      - "traefik.http.services.mein-solar-system.loadbalancer.server.port=80"
      - "glance.title=Mein Solar System"
      - "glance.url=https://system.saturn.mein.nl"
      - "glance.description=A interactive solar system"
      - "glance.icon=si:planetscale"
