version: "3.9"

services:
  mein-solar-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mein-solar-system
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mein-solar-system.rule=Host(`mein-solar-system.example.com`)"
      - "traefik.http.services.mein-solar-system.loadbalancer.server.port=80"
    ports:
      - "8080:80" # Optional: Expose locally for testing
